openapi: 3.1.0
info:
  version: 1.0.0
  title: Tasteorama api-docs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Documentation of Testeorama foodle server.
tags:
  - name: Testeorama foodle server
    description: Operations about recipes.
  - name: Auth
    description: Auth operations.
servers:
  - url: https://pg10-foodle-server.onrender.com
paths:
  /api/auth/register:
    post:
      $ref: '../swagger/path/auth/register.yaml'
  /api/auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /api/auth/logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml
  /api/auth/refresh:
    post:
      $ref: ../swagger/path/auth/refresh.yaml
  /api/auth/google-oauth-url:
    get:
      $ref: ../swagger/path/auth/google-oauth.yaml
  /api/auth/confirm-oauth:
    post:
      $ref: ../swagger/path/auth/confirm-oauth.yaml
  /api/users/current:
    get:
      $ref: ../swagger/path/users/get.yaml
  /api/categories:
    get:
      $ref: ../swagger/path/categories/get.yaml
  /api/ingredients:
    get:
      $ref: ../swagger/path/ingredients/get.yaml
  /api/recipes/favorite:
    get:
      $ref: ../swagger/path/recipes/favorite/get.yaml
  /api/recipes/{recipeId}/favorite:
    post:
      $ref: ../swagger/path/recipes/{id}/favorite/post.yaml
    delete:
      $ref: ../swagger/path/recipes/{id}/favorite/delete.yaml
  /api/recipes/own:
    get:
      $ref: ../swagger/path/recipes/own/get.yaml
  /api/recipes:
    get:
      $ref: ../swagger/path/recipes/get.yaml
    post:
      $ref: ../swagger/path/recipes/post.yaml
  /api/recipes/{recipeId}:
    get:
      $ref: ../swagger/path/recipes/{id}/get.yaml
    delete:
      $ref: ../swagger/path/recipes/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
