type: object
required:
  - _id
  - title
  - category
  - owner
  - instructions
  - description
  - time
  - ingredients
  - createdAt
  - updatedAt
properties:
  _id:
    type: string
    description: Recipe id
    example: 6462a8f74c3d0ddd2889806d
  title:
    type: string
    description: Recipe title
    example: Rogaliki (Polish Croissant Cookies)
  category:
    type: string
    description: Recipe category
    example: Dessert
  owner:
    type: object
    properties:
      _id:
        type: string
        example: 64c8d958249fae54bae90bb9
      name:
        type: string
        example: Larry Pageim
      avatar:
        type:
          - integer
          - 'null'
        example: null
      email:
        type: string
        example: larry@gmail.com
  area:
    type: string
    description: Recipe origin area
    example: Polish
  instructions:
    type: string
    description: Recipe instructions
    example: In a medium bowl mix egg yolks, philly cheese and baking powder using...
  description:
    type: string
    description: Recipe description
    example: A popular Polish pastry, Rogaliki are crescent-shaped cookies made fro...
  thumb:
    type: string
    format: url
    description: Recipe photo url
    example: https://ftp.goit.study/img/so-yummy/preview/Rogaliki%20_Polish%20Croissant%20Cookies_.jpg
  time:
    type: string
    description: Cooking time in minutes
    example: 35
  ingredients:
    type: array
    items:
      type: object
      properties:
        id:
          type: object
          properties:
            _id:
              type: string
              example: 640c2dd963a319ea671e367e
            name:
              type: string
              example: Butter
            desc:
              type: string
              example: A dairy product made from churning cream or milk, with a high fat content and a creamy, rich flavor that is often used in cooking and baking.
            img:
              type: string
              format: url
              example: https://ftp.goit.study/img/so-yummy/ingredients/640c2dd963a319ea671e367e.png
        measure:
          type: string
          example: 50g
        _id:
          type: string
          example: 68683d8a969e7da7a2b39b3a
  createdAt:
    type: string
    format: date-time
    description: Recipe created at
    example: 2025-06-20T14:51:07.199+00:00
  updatedAt:
    type: string
    format: date-time
    description: Recipe last updated at
    example: 2025-06-21T14:51:07.199+00:00
